### ISSUE TITLE
[BUG] stqdm in for loop with the enumerate function

### ISSUE THREAD

**Issue by apolinario** [Wirg/stqdm#16]
**Describe the bug**

stqdm doesn't work on a python loop that uses the enumerate function 

**To Reproduce**
```
values = ["a", "b", "c"]
for count, value in stqdm(enumerate(values)):
    sleep(1)
```
doesn't work. 

However
```
values = ["a", "b", "c"]
for value in stqdm(values)):
    sleep(1)
```
works normally

**Comment by apolinario** [comment]
Also more broadly, even without the `enumerate` function, it doesn't work when it is iterating over a `generator` too

**Comment by Wirg** [comment]
Hi @apolinario!

Thanks for the report and for the examples. Sorry for the late reply.

> Also more broadly, even without the `enumerate` function, it doesn't work when the for loop is iterating over any `generator` it seems
To be exact, it's about iteratables without length. 
When you pass your list into enumerate you lose the initial length of the object.

stqdm & tqdm have no way to know when your object will end and can not implement a progress bar.
In this situation, tqdm just return the number of iteration by seconds and the total number of iterations in text.
Like this :
```
0it [00:00, ?it/s]
1it [00:01,  1.00s/it]
2it [00:02,  1.00s/it]
3it [00:03,  1.00s/it]
```

I can and will probably implement this in the next release.
Is this what you will be expecting?

If you want the full progress bar tho, you have 2 solutions :
- provide the expected number of iterations using total (tqdm API) :
```python
from stqdm import stqdm
from time import sleep

values = ["a", "b", "c"]
for count, value in stqdm(enumerate(values), total=len(values)):
    sleep(1)
```
- in your case,  add the enumerate outside `stqdm` call so that stqdm/tqdm can take the length of the original object as a default total

```python
from stqdm import stqdm
from time import sleep

values = ["a", "b", "c"]
for count, value in enumerate(stqdm(values)):
    sleep(1)
```

**Comment by Wirg** [comment]
In the incoming v0.0.5 version, there should be a fix that display the iteration speed without a real progress as there is no total or length.

![image](https://user-images.githubusercontent.com/17848620/191012098-44c4ba13-1907-438a-a868-e5d1c0647961.png)

**Comment by Wirg** [comment]
v0.0.5 is live : https://github.com/Wirg/stqdm/releases/tag/v0.0.5 .

In this version, you will have a text displaying the number of iterations and the iterations speed (like with tqdm).
See example here : https://github.com/Wirg/stqdm/blob/096605ed7b619affd0cabaaf237b98ee6e96e981/examples/stqdm_no_total_no_length.py  .
You won't have a progress bar as there is no knowledge of the length of the iteration. It's often better to provide `total=expected_length` to the `stqdm.__init__` .
